# Generated by Django 5.2.7 on 2025-10-12 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='pdfs/original/')),
                ('edited_file', models.FileField(blank=True, null=True, upload_to='pdfs/edited/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
